### ISSUE TITLE
Automatic Copyright Year

### ISSUE THREAD

**Issue by michaelthorne** [bradfrost/patternlab#23]
As seen on CSS Tricks: http://css-tricks.com/snippets/php/automatic-copyright-year/

`&copy; <?php echo date("Y") ?>`

This is to fix the current, hard-coded 2013 in: patterns/02-Organisms/00-Global/01-Footer.php

**Comment by bradfrost** [comment]
Hey @michaelthorne, thanks for the suggestion. I'm going to pass on implementing this because Pattern Lab is meant to be language agnostic, and this is also a very specific case. Pattern Lab is about the underlying system, rather than the demo code we provide.

**Comment by michaelthorne** [comment]
@bradfrost That makes perfect sense. I just had a look at the PHP version of Pattern Lab and thought my previous comment (issue) would've applied there. But I see you're using Mustache templates which is great.

Thanks for a great project!

**Comment by bradfrost** [comment]
Yeah, the PHP is really just used behind the scenes to generate the site.
