### ISSUE TITLE
Pattern Lab website is down

### ISSUE THREAD

**Issue by akshatkedia** [bradfrost/patternlab#25]
Just noticed, Pattern Lab website is down: [http://patternlab.bradfrostweb.com/](http://patternlab.bradfrostweb.com/)

It is showing the Server Default Page.

**Comment by bradfrost** [comment]
Hi @akshatkedia,
The address for the Pattern Lab website is: http://patternlab.io/

Where did you encounter this URL? I can update accordingly.

**Comment by akshatkedia** [comment]
Hi @bradfrost ,

In the Pattern Lab section of this blog post: [http://bradfrost.com/blog/post/atomic-web-design/](http://bradfrost.com/blog/post/atomic-web-design/)

**Comment by bradfrost** [comment]
Great, I just updated the post. Thanks for pointing it out!

**Comment by akshatkedia** [comment]
Most welcome :smile:
